version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: DockerfileFrontend
    ports:
      - "80:80"
    environment:
      - DISABLE_IPV6=1
    networks:
      - app_network
    restart: always

networks:
  app_network:
    external: true
